language: node_js
before_install: "! grep PLEASE_FILL_IN_HERE README.md"
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
node_js:
  - '7'
  - '8'
env:
  - TEST_DATABASE_URL=''
  - TEST_DATABASE_URL='postgres://localhost/travis_ci_test'
